name: mdaq
description: Qwhizy.
publish_to: 'Play Store'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.0
  flutter_svg: ^2.0.7
  url_launcher: ^6.0.12
  http: ^1.1.0
  audioplayers: ^5.2.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.4
  fl_chart: ^0.64.0
  percent_indicator: ^4.0.1
  intl: ^0.18.1
  dots_indicator: ^2.1.1

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/ic_launcher_rounded_square.png"
  adaptive_icon_bacground: "#ffffff"
  adaptive_icon_foreground: "assets/icons/ic_launcher_rounded_square.png"

flutter_native_splash:
  android: false
  ios: false
  web: false

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/chars/
    - assets/icons/
  fonts:
    - family: Baloo
      fonts:
        - asset: assets/fonts/baloo/Baloo-Regular.ttf
    - family: Baloo2
      fonts:
        - asset: assets/fonts/baloo2/Baloo2-Regular.ttf
        - asset: assets/fonts/baloo2/Baloo2-Bold.ttf
          weight: 700